version: '3.8'


services:

  nginx:
    depends_on:
      - backend
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./stocks_products/static:/static
      - ./nginx.conf:/etc/nginx/conf.d/dfault.conf
  backend:
    build: .
    image: new_python
    ports:
      - '8000:8000'
    environment:
      POSTGRES_DB: "netology_stocks_products"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "masterkey"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    depends_on:
      - postgres
  postgres:
    image: postgres:11.0-alpine
    environment:
      POSTGRES_DB: "netology_stocks_products"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "masterkey"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    ports:
      - '5432:5432'

